Metron-Project/metron-tagger

- tests/conftest.py
This PR aims to improve test reliability of test `test_sort_comic` by altering fixture scope of `fake_comic` to "function".
The test can fail in this way by running `pip3 install pytest-repeat; python3 -m pytest --count=2 tests/test_taggerlib_filesorter.py::test_sort_comic`:
```
comic = ComicArchive(fake_comic)
if comic.has_metadata():
comic.remove_metadata()
>       comic.write_metadata(fake_metadata)
tests/test_taggerlib_filesorter.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.local/lib/python3.8/site-packages/darkseid/comicarchive.py:276: in write_metadata
write_success = …
```
> Altering fixture scope of `fake_comic` to "function"

- metrontagger/main.py
- metrontagger/options.py
- poetry.lock
- pyproject.toml
- tests/test_metron_tagger.py
This PR adds the following enhancements:
- Allow user to write metadata tags to a cb7 (7zip) archive.
- Export existing cbz (Zip) archive to a *new* cb7 archive.
> Add 7zip support

- metrontagger/utils.py
- tests/test_utils.py
Titles with '/' in them have it substitued with ' - '.
Let's remove that for better seach results
> Improve series name matching

- metrontagger/filesorter.py
- tests/conftest.py
- tests/test_filesorter.py
Sort Trade Paperbacks to own folder to prevent filename collisions.
> Sort Trade Paperback to own folder

- metrontagger/talker.py
Tag `CCA` rating as `Everyone` in ComicInfo tags
> Handle `CCA` ratings correctly

- metrontagger/filerenamer.py
- metrontagger/utils.py
Issue on Metron use `½` for numbering, but that doesn't play well with some filesystems, so we'll use `.5` (user pad setting) when we rename the file.
> Handle matching of issue #½ better

- metrontagger/filerenamer.py
- tests/conftest.py
- tests/test_filerenamer.py
Use abbreviated words for 'Hard Cover' & 'Trade Paperback', since this is fairly common for file naming.
> Improve handling of series format better

- metrontagger/settings.py
Remove migrate_old_config() method. It shouldn't be needed any longer.
> Remove Unused Method

- metrontagger/utils.py
- poetry.lock
- pyproject.toml
- tests/test_talker.py
- tests/test_utils.py
Use `comicfn2dict` for filename parsing.
Thanks to @ajslater for creating this library.
> comicfn2dict

- metrontagger/logging.py
- metrontagger/run.py
- metrontagger/talker.py
- metrontagger/utils.py
- poetry.lock
- pyproject.toml
- tests/test_utils.py
Instead of passing 'volume' & 'year' params to Metron's issue endpoint, let's return a larger result set.
That way we can compare the issue's cover hash to get the right one. Based on my initial testing this works pretty well, tho older issues with bad cover's may not give that great of results.
If it turns out this doesn't work for most user's, we can look at using the 'volume' and 'year' to narrow down the results.
> Improve Matching

- metrontagger/styles.py
- metrontagger/talker.py
If a user's comic was already tagged with information with **ComicTagger** or **Metron-Tagger** we can get either the CVID or Metron ID and use that info to refresh the `ComicInfo.xml` data.
If the comic has a CVID and that info isn't available it will fall back to using the comic filename to search.
> Use existing `ComicInfo.xml` to identify comic

- metrontagger/utils.py
- tests/test_utils.py
Remove commas and `&` from the series name before querying Metron.
> Strip commas and `&` from series name

- NEWS.md
- metrontagger/duplicates.py
Let's skip any image that raises a `UnidentifiedImageError`
> Handle Image Exception in Duplicates module

- metrontagger/talker.py
If the comic has an existing `ComicInfo.xml` we need to check that the `Notes` element exists.
> Fix Tagging Bug with Existing `ComicInfo.xml`

- .pre-commit-config.yaml
- metrontagger/duplicates.py
- metrontagger/filerenamer.py
- metrontagger/run.py
- metrontagger/settings.py
- metrontagger/talker.py
- metrontagger/validate_ci.py
- poetry.lock
- pyproject.toml
- tests/test_duplicates.py
Some refactoring to improve performance.
> Performance Refactoring

- metrontagger/filesorter.py
- metrontagger/talker.py
- poetry.lock
- pyproject.toml
Minor change to add support for the `Imprint` field.
Will add the `Imprint` element to the ComicInfo.xml if present.
Also, modified filesorter.py to continue current sorting option. I.e. Use `Vertigo` instead of `DC Comics` when sorting.
In a future release, I'll rework the sorting code to give the user the option on how they want to handle it.
> Add imprint support

- .github/workflows/ruff.yml
- .pre-commit-config.yaml
- metrontagger/duplicates.py
- metrontagger/talker.py
- poetry.lock
Don't really care about corrupt EXIF data, so let's ignore the warning.
> Ignore `Corrupt EXIF data` warnings

- metrontagger/talker.py
- Ask for user interaction *after* searching for all comics.
- Remove redundant assignments to issue_id and multiple_match at the beginning.
- Simplify nested conditionals by combining conditions where possible.
- Use early returns to reduce the depth of nested conditionals.
> Fix User Matching Interaction

- metrontagger/talker.py
Ask for user interaction *after* all comics have been searched if multiple results without cover hash within hamming distance are found
> Remove Interruption in Matching Process

- metrontagger/cli.py
- metrontagger/options.py
- metrontagger/run.py
- metrontagger/settings.py
- metrontagger/talker.py
- metrontagger/utils.py
- poetry.lock
- pyproject.toml
This PR adds the ability to migrate the data from a ComicInfo.xml to a MetronInfo.xml if it does not already exist.
> Add ComicInfo -> Metroninfo Migration Function

- metrontagger/talker.py
- poetry.lock
- pyproject.toml
This PR has the following changes:
- Refactor `_get_id_from_comic_info` to use Darkseid helper function
- Bump minimum version of Darkseid
> Refactor `_get_id_from_comic_info` 

- metrontagger/talker.py
- metrontagger/utils.py
- tests/test_utils.py
This PR fixes a bug where the filename parser doesn't provide a series name value in the metadata.
If the metadata doesn't have a series name we return `None`, and print a message to the user that we couldn't parse the filename.
An example of this would be the filename "Heavy Metal #319 (2022).cbz", where comicfn2dict assumes that Heavy Metal is the publisher, not the series name.
> Fix Filename Metadata Bug

- metrontagger/options.py
- metrontagger/talker.py
- tests/test_talker.py
As discussed in #180, if a search results in only a single valid match, even if the cover match doesn't meet the required threshold for an auto-match, if --accept-only is passed, then accept it anyway. This should result in a much smoother (less interactive) import for cases where the filename is already well-matched.
> Add --accept-only option to automatically accept single valid matches

- metrontagger/options.py
- metrontagger/run.py
- metrontagger/talker.py
- metrontagger/utils.py
- tests/test_options.py
Change the behaviour of `--id` when more than one file is passed in (after resolving recursively, filtering, etc).
Currently, `--id` fails if more than one file is passed in, because it's interpreted as an issue ID and it obviously
doesn't make sense to tag multiple files with the same issue. But now it is assumed that if you're passing in --id
with multiple files, you intend for `--id` to represent a series id rather than an issue id. All files being passed
in are assumed to belong to that series, and all results from the metron API are filtered down to ones that match
that series.
Originally I used the existing call to /issues but then I realized I can just pass the series_id to /issues directly
and avoid an extra call to fetch series metadata. So now it all works server-side without …
> Interpret --id as a series id if more than one file is passed in

- metrontagger/utils.py
- tests/test_utils.py
This PR refactors the `create_query_params` function. The changes include:
- Stripping `TPB`, `HC`, and `Digital Chapter` from the series name before querying Metron.
- When stripping leading zeroes from the issue number, make sure if the issue number is zero that is set it as "0"
- Split out the function into smaller functions.
- Add tests for corner-cases.
> Refactor `create_query_params`

- metrontagger/talker.py
This PR fixes a potential bug is the `hex_to_hash` method fails
> Gracefully handle `hex_to_hash` ValueError exception
