- metrontagger/metron_tagger.py
Substitute colon for hyphen when searching for the series name
> Improve series search results

- metrontagger/metron_tagger.py
- metrontagger/taggerlib/utils.py
- tests/test_taggerlib_utils.py
Refactor the online issue search function, so that issues with multiple matches that require user intervention are handled _after_ all the issues have been searched.
> Improve usability of multiple issue matches

- metrontagger/main.py
Refactor the code for ignore existing files with metadata when searching online, so the output is cleaner.
> Fix handling of files that already have metadata

- Pipfile.lock
- metrontagger/main.py
- metrontagger/taggerlib/filerenamer.py
- metrontagger/taggerlib/filesorter.py
- metrontagger/taggerlib/metrontalker.py
- metrontagger/taggerlib/utils.py
- tests/test_taggerlib_filesorter.py
Update code for api changes to Darkseid
> Darkseid api changes

- metrontagger/taggerlib/filesorter.py
- tests/test_taggerlib_filesorter.py
Add a new test to filesorter and remove a redundant check for metadata
> New tests 🎂

- .travis.yml
- metrontagger/__init__.py
- setup.cfg
Update travis.yml to deploy on tag.
> Travis push 🔨

- metrontagger/taggerlib/filesorter.py
- tests/test_taggerlib_filesorter.py
Minor cleanup in the FileSorter() class
> File sorter cleanup

- tests/conftest.py
- tests/test_metron_tagger.py
- tests/test_taggerlib_metrontalker.py
- tests/test_taggerlib_options.py
- tests/test_taggerlib_settings.py
- tests/test_taggerlib_utils.py
Rewrite some tests to use pytest.
> More tests 🎂

- metrontagger/taggerlib/utils.py
- tests/test_taggerlib_utils.py
* If the file doesn't have an issues number let's assume it's "1"
> Fix comic files that don't have issue number

- metrontagger/filerenamer.py
- metrontagger/main.py
- metrontagger/settings.py
- pyproject.toml
- tests/test_settings.py
Allow users to use cutom template for renaming comic files.
> Use custom rename template

- metrontagger/main.py
- metrontagger/options.py
- metrontagger/talker.py
- tests/test_talker.py
Ask the user for confirmation before writing a tag to the comic fie.
> Add support for interactive querying

- metrontagger/__init__.py
- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/test_metron_tagger.py
- tests/test_talker.py
Update for api change in latest version of mokarri.
> Update for mokarri

- poetry.lock
- pyproject.toml
> Update to latest version of mokkari

- .github/workflows/pypi.yml
> Add gh action for pypi uploading

- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/main.py
- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/test_metron_tagger.py
Used questionary for print style improvements and multiple matches interactions.
> Improve screen output

- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/test_talker.py
Write genre tags to ComicInfo.xml if present
> Add genre support

- .github/workflows/testing.yml
- README.rst
- metrontagger/cli.py
- metrontagger/options.py
- metrontagger/run.py
- metrontagger/settings.py
- metrontagger/utils.py
- poetry.lock
- pyproject.toml
- tests/test_talker.py
- tox.ini
> Add CBR support

- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_filerenamer.py
- tests/test_filesorter.py
- tests/test_metron_tagger.py
- tests/test_talker.py
Update to latest Darkseid to fix this.
> Write `Format` Element to ComicInfo.xml

- metrontagger/cli.py
- metrontagger/options.py
- metrontagger/run.py
- tests/test_options.py
Instead of command line options for saving info,  let's ask the user interactively for it.
> Ask user interactively for options

- metrontagger/filesorter.py
- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_filesorter.py
- tests/test_talker.py
This is another step in supporting future comic metadata formats.
> Update to Darkseid-1.4.0 api

- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/run.py
- metrontagger/talker.py
- metrontagger/utils.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_filerenamer.py
- tests/test_filesorter.py
- tests/test_metron_tagger.py
- tests/test_talker.py
> Darkseid-2.0

- metrontagger/filerenamer.py
- poetry.lock
Use correct attribute for metadata language.
> Fix Comic Renamer bug

- metrontagger/talker.py
- poetry.lock
- tests/test_talker.py
Add Age Rating information to written tags
> Support for Age Rating

- metrontagger/talker.py
- poetry.lock
- pyproject.toml
- tests/test_talker.py
Currently using a hamming distance of 10 since it produces pretty decent results
> Use cover hash to improve matching

- .github/workflows/changelog-ci.yml
- changelog-ci-config.json
- metrontagger/__init__.py
- poetry.lock
- pyproject.toml
> Add Changelog GitHub action - v1.6.4

- README.rst
- pyproject.toml
Update the README.rst & don't add the CHANGELOG.md to the wheel package.
> Release 1.6.4

- metrontagger/talker.py
Added some error handling and some minor refactoring
> Minor Refactoring

- package-lock.json
- poetry.lock
> Update Pillow and Other Deps

- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/utils.py
- package-lock.json
- poetry.lock
- tests/test_filesorter.py
Fix some typing to quite PyRight
> Type Annotation Fixes

- metrontagger/duplicates.py
- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/run.py
- metrontagger/settings.py
- metrontagger/talker.py
- metrontagger/validate_ci.py
- poetry.lock
- pyproject.toml
> Refactoring

- metrontagger/cli.py
- metrontagger/duplicates.py
- metrontagger/filerenamer.py
- metrontagger/filesorter.py
- metrontagger/run.py
- metrontagger/settings.py
- metrontagger/styles.py
- metrontagger/talker.py
- metrontagger/utils.py
- metrontagger/validate_ci.py
- pyproject.toml
- tests/test_duplicates.py
- tests/test_logging.py
- tests/test_validate.py
Add some missing tests and docstrings
> Add Tests & Docstrings

- metrontagger/filerenamer.py
- tests/test_filerenamer.py
Minor fix to correctly rename Hardcover's based on the recent change on Metron.
> UIpdate for Hardcover Naming Change

- metrontagger/filerenamer.py
Add `Digital Chapter` to format mapping dict
> Add New Format Name to mapping in FileRenamer class

- package-lock.json
- poetry.lock
- pyproject.toml
- tests/test_talker.py
> Update Project Dependencies

- metrontagger/talker.py
Ignore existing ComicInfo or MetronInfo depending on what's being searched for
> Fix ignore existing option

- metrontagger/filerenamer.py
Missed updating the Darkseid metadata changes
> Fix Rename Bug

- poetry.lock
- pyproject.toml
Use the latest bug fix version of Darkseid
> Require latest Darkseid

- metrontagger/run.py
This PR adds a note to the MetronInfo when migrating from a ComicInfo
> Add note to MetronInfo when migrating from ComicInfo

- metrontagger/talker.py
Forgot to add Universes to mapping
> Write Universe metadata to MetronInfo.xml

- metrontagger/talker.py
- poetry.lock
- pyproject.toml
This PR will add the `gcd_id` to the metadata, and if the xml supports it, write to file
> Add `gcd_id` to metadata

- metrontagger/talker.py
- poetry.lock
This PR simple adds the `collection title` response info to the metadata.
> Write `Collection Title` to MetronInfo.xml

- metrontagger/utils.py
- tests/test_utils.py
Simple little PR to handle float|int when using cleanup_string()
> Handle floats in cleanup_string()

- Makefile
- bin/version.sh
This PR improves the version script by leveraging uv version to update version by semantic values.
Ex. $ make version V=major
> Improve version.sh

- metrontagger/talker.py
This PR caches the comic's cover hash when comparing to the results from Metron.
> Cache the results when getting a comic's cover hash.

- tests/test_talker.py
This PR rewrites the Talker tests.
> Rewrite talker tests to increase coverage

- metrontagger/duplicates.py
- metrontagger/run.py
This PR show the user comic size savings when removing duplicate pages.
The `DuplicateIssue` dataclass is enhanced with the following:
- `Automatic Size Tracking`: The class now automatically captures the starting file size when initialized
- `Ending Size Updates`: Added update_ending_size() method to capture file size after processing
- `Size Calculations`: Methods to calculate size reduction in bytes and percentage
- `Human-Readable Formatting`: Static method to format file sizes (B, KB, MB, GB, TB)
> Display Duplicate Page Remove Statistics

- README.rst
- metrontagger/filesorter.py
- metrontagger/run.py
- metrontagger/talker.py
- pyproject.toml
- tests/test_filesorter.py
- uv.lock
This PR updates the project to use darkseid-6.0.0
> Update for Darkseid-6.0.0
